"""
PR Description Generator

Generates PR descriptions from roadmap task context.

Task: git-integration-2-task-006
"""

import yaml
from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass

from vibey.operations.git.branch_linker import BranchLinker


@dataclass
class TaskInfo:
    """Task information for PR description."""
    id: str
    name: str
    description: str
    status: str
    priority: str
    estimated_hours: Optional[int]
    assigned_agent: Optional[str]
    sprint_id: str
    sprint_name: str
    track_id: str
    track_name: str
    dependencies: List[str]
    blocks: List[str]
    blocked_by: List[str]
    quality_gates: List[Dict]
    branch_name: Optional[str]
    commits: List[str]


class PRDescriptionGenerator:
    """
    Generate PR descriptions from task context.

    Reads task information from roadmap YAML and generates
    formatted PR descriptions with context, checklists, and metadata.
    """

    DEFAULT_TEMPLATE = """## Summary

**Task:** {task_id}
**Sprint:** {sprint_name} ({sprint_id})
**Track:** {track_name}

{description}

## Changes

{changes_checklist}

## Testing

{testing_checklist}

## Related Tasks

{related_tasks}

## Quality Gates

{quality_gates}

## Context

- **Priority:** {priority}
- **Estimated Hours:** {estimated_hours}
{branch_info}
{commits_info}

---
*Generated by Vibey from task: {task_id}*
"""

    def __init__(self, repo_path: str = "."):
        """
        Initialize PR description generator.

        Args:
            repo_path: Path to repository root
        """
        self.repo_path = Path(repo_path).resolve()
        self.roadmap_dir = self.repo_path / ".vibey" / "roadmap"
        self.branch_linker = BranchLinker(repo_path)

    def find_task_file(self, task_id: str) -> Optional[Path]:
        """
        Find the task YAML file in flat structure.

        Args:
            task_id: Task ID to search for

        Returns:
            Path to task YAML file, or None if not found
        """
        if not self.roadmap_dir.exists():
            return None

        # Direct lookup in flat tasks/ directory
        task_file = self.roadmap_dir / "tasks" / f"{task_id}.yaml"
        if task_file.exists():
            return task_file

        # Fallback: scan tasks directory for matching ID
        tasks_dir = self.roadmap_dir / "tasks"
        if tasks_dir.exists():
            for task_file in tasks_dir.glob("*.yaml"):
                if task_file.name.startswith('.'):
                    continue
                try:
                    with open(task_file) as f:
                        data = yaml.safe_load(f)
                    if data and 'task' in data:
                        if data['task'].get('id') == task_id:
                            return task_file
                except Exception:
                    continue

        return None

    def load_task_info(self, task_id: str) -> Optional[TaskInfo]:
        """
        Load complete task information from flat structure.

        Args:
            task_id: Task ID

        Returns:
            TaskInfo object, or None if not found
        """
        task_file = self.find_task_file(task_id)

        if not task_file:
            return None

        try:
            with open(task_file) as f:
                data = yaml.safe_load(f)

            task = data.get("task", {})
            if not task:
                return None

            sprint_id = task.get("sprint_id", "unknown")
            track_id = task.get("track_id", "unknown")

            # Load sprint info from flat structure
            sprint_name = "Unknown Sprint"
            quality_gates = []
            sprint_file = self.roadmap_dir / "sprints" / f"{sprint_id}.yaml"
            if sprint_file.exists():
                with open(sprint_file) as f:
                    sprint_data = yaml.safe_load(f)
                    sprint_info = sprint_data.get("sprint", {})
                    sprint_name = sprint_info.get("name", "Unknown Sprint")
                    quality_gates = sprint_info.get("quality_gates", [])

            # Load track info from flat structure
            track_name = "Unknown Track"
            track_file = self.roadmap_dir / "tracks" / f"{track_id}.yaml"
            if track_file.exists():
                with open(track_file) as f:
                    track_data = yaml.safe_load(f)
                    track_info = track_data.get("track", {})
                    track_name = track_info.get("name", "Unknown Track")

            # Get branch info
            branch_info = self.branch_linker.get_task_branch(task_id)
            branch_name = branch_info.branch_name if branch_info else None

            # Build TaskInfo
            return TaskInfo(
                id=task.get("id", task_id),
                name=task.get("title", task.get("name", "Untitled Task")),
                description=task.get("description", ""),
                status=task.get("status", "not_started"),
                priority=task.get("priority", "medium"),
                estimated_hours=task.get("estimated_hours"),
                assigned_agent=task.get("assigned_agent"),
                sprint_id=sprint_id,
                sprint_name=sprint_name,
                track_id=track_id,
                track_name=track_name,
                dependencies=task.get("dependencies", []),
                blocks=task.get("blocks", []),
                blocked_by=task.get("blocked_by", []),
                quality_gates=quality_gates,
                branch_name=branch_name,
                commits=task.get("commits", [])
            )

        except Exception:
            return None

    def extract_checklist_from_description(self, description: str) -> List[str]:
        """
        Extract checklist items from task description.

        Args:
            description: Task description text

        Returns:
            List of checklist items
        """
        lines = description.split('\n')
        checklist = []

        for line in lines:
            stripped = line.strip()
            # Look for bullet points or numbered items
            if stripped.startswith('- ') or stripped.startswith('* '):
                item = stripped[2:].strip()
                if item:
                    checklist.append(item)
            elif stripped and stripped[0].isdigit() and '. ' in stripped:
                item = stripped.split('. ', 1)[1].strip()
                if item:
                    checklist.append(item)

        return checklist

    def generate_changes_checklist(self, task: TaskInfo) -> str:
        """
        Generate checklist of changes from task description.

        Args:
            task: TaskInfo object

        Returns:
            Formatted checklist markdown
        """
        items = self.extract_checklist_from_description(task.description)

        if not items:
            # Generate default checklist
            items = [
                f"Implement {task.name}",
                "Add unit tests",
                "Update documentation"
            ]

        checklist_md = "\n".join([f"- [ ] {item}" for item in items])
        return checklist_md

    def generate_testing_checklist(self, task: TaskInfo) -> str:
        """
        Generate testing checklist.

        Args:
            task: TaskInfo object

        Returns:
            Formatted testing checklist markdown
        """
        items = [
            "Unit tests pass",
            "Integration tests pass",
            "Manual testing completed",
            "Edge cases covered"
        ]

        checklist_md = "\n".join([f"- [ ] {item}" for item in items])
        return checklist_md

    def generate_related_tasks(self, task: TaskInfo) -> str:
        """
        Generate related tasks section.

        Args:
            task: TaskInfo object

        Returns:
            Formatted related tasks markdown
        """
        sections = []

        if task.dependencies:
            deps = "\n".join([f"- {dep}" for dep in task.dependencies])
            sections.append(f"**Depends on:**\n{deps}")

        if task.blocks:
            blocks = "\n".join([f"- {block}" for block in task.blocks])
            sections.append(f"**Blocks:**\n{blocks}")

        if task.blocked_by:
            blocked = "\n".join([f"- {blocker}" for blocker in task.blocked_by])
            sections.append(f"**Blocked by:**\n{blocked}")

        if not sections:
            return "*No related tasks*"

        return "\n\n".join(sections)

    def generate_quality_gates(self, task: TaskInfo) -> str:
        """
        Generate quality gates section.

        Args:
            task: TaskInfo object

        Returns:
            Formatted quality gates markdown
        """
        if not task.quality_gates:
            return "*No quality gates defined*"

        lines = []
        for gate in task.quality_gates:
            name = gate.get("name", "Unknown Gate")
            threshold = gate.get("threshold", 0)
            blocking = gate.get("blocking", False)
            status = gate.get("status", "not_run")

            status_emoji = {
                "passed": "✅",
                "failed": "❌",
                "not_run": "⏳"
            }.get(status, "❓")

            blocking_text = " (blocking)" if blocking else ""

            lines.append(f"- {status_emoji} **{name}**{blocking_text}: {threshold}%")

        return "\n".join(lines)

    def generate_description(
        self,
        task_id: str,
        template: Optional[str] = None,
        include_branch: bool = True,
        include_commits: bool = True
    ) -> Optional[str]:
        """
        Generate PR description for a task.

        Args:
            task_id: Task ID
            template: Custom template (uses default if None)
            include_branch: Include branch information
            include_commits: Include commits list

        Returns:
            Formatted PR description, or None if task not found
        """
        task = self.load_task_info(task_id)

        if not task:
            return None

        # Use provided template or default
        template_str = template or self.DEFAULT_TEMPLATE

        # Generate sections
        changes_checklist = self.generate_changes_checklist(task)
        testing_checklist = self.generate_testing_checklist(task)
        related_tasks = self.generate_related_tasks(task)
        quality_gates = self.generate_quality_gates(task)

        # Branch info
        branch_info = ""
        if include_branch and task.branch_name:
            branch_info = f"- **Branch:** {task.branch_name}"

        # Commits info
        commits_info = ""
        if include_commits and task.commits:
            commits_list = ", ".join([c[:7] for c in task.commits[:5]])
            if len(task.commits) > 5:
                commits_list += f" (+{len(task.commits) - 5} more)"
            commits_info = f"- **Commits:** {commits_list}"

        # Format template
        description = template_str.format(
            task_id=task.id,
            task_name=task.name,
            description=task.description,
            sprint_id=task.sprint_id,
            sprint_name=task.sprint_name,
            track_id=task.track_id,
            track_name=task.track_name,
            priority=task.priority,
            estimated_hours=task.estimated_hours or "Not specified",
            changes_checklist=changes_checklist,
            testing_checklist=testing_checklist,
            related_tasks=related_tasks,
            quality_gates=quality_gates,
            branch_info=branch_info,
            commits_info=commits_info
        )

        return description

    def detect_task_from_branch(self) -> Optional[str]:
        """
        Detect task ID from current branch name.

        Returns:
            Task ID if detected, None otherwise
        """
        current_branch = self.branch_linker.get_current_branch()

        if not current_branch:
            return None

        branch_type, item_id = self.branch_linker.parse_branch_name(current_branch)

        if branch_type.value == "task" and item_id:
            return item_id

        return None


def generate_pr_description(
    task_id: Optional[str] = None,
    repo_path: str = ".",
    template: Optional[str] = None,
    auto_detect: bool = True
) -> Optional[str]:
    """
    Convenience function to generate PR description.

    Args:
        task_id: Task ID (auto-detects from branch if None and auto_detect=True)
        repo_path: Repository path
        template: Custom template
        auto_detect: Auto-detect task from branch name

    Returns:
        PR description markdown, or None if task not found
    """
    generator = PRDescriptionGenerator(repo_path)

    # Auto-detect task from branch if not provided
    if not task_id and auto_detect:
        task_id = generator.detect_task_from_branch()

    if not task_id:
        return None

    return generator.generate_description(task_id, template)
