"""
Claude Code Platform Adapter

Generates Claude Code deployments from .vibey/config/ to .claude/ directory.

Usage:
    from framework.platform_adapters.claude_adapter import ClaudeAdapter

    adapter = ClaudeAdapter()
    adapter.deploy()

Created: 2025-11-09
Sprint: core-framework-2, Task 6
"""

from pathlib import Path
from typing import Dict, List
from .base import PlatformAdapter


class ClaudeAdapter(PlatformAdapter):
    """
    Platform adapter for Claude Code.

    Generates deployments in .claude/ directory with:
    - CLAUDE.md (main instructions file)
    - agents/<agent-id>.md (agent files)
    - workflows/<workflow-id>.md (workflow files)
    """

    def get_platform_name(self) -> str:
        """Return platform name."""
        return "claude-code"

    def get_deployment_dir(self) -> Path:
        """Return .claude/ deployment directory."""
        # Get project root (parent of .vibey/)
        project_root = self.vibey_dir.parent
        return project_root / ".claude"

    def get_instructions_filename(self) -> str:
        """Return CLAUDE.md filename."""
        return "CLAUDE.md"

    def generate_instructions_file(self) -> str:
        """
        Generate CLAUDE.md content.

        Uses claude.md.j2 template if available, otherwise generates
        structured default content.
        """
        # Load all configs
        project_config = self.load_project_config()
        framework_config = self.load_framework_config()
        agents = self.load_all_agents()
        workflows = self.load_all_workflows()
        quality_gates = self.load_quality_gates()

        # Prepare template context
        context = {
            'project': project_config.get('project', {}),
            'tech_stack': project_config.get('tech_stack', {}),
            'development': project_config.get('development', {}),
            'framework': framework_config,
            'agents': agents,
            'workflows': workflows,
            'quality_gates': quality_gates,
            'platform': 'claude-code'
        }

        # Try to render template
        try:
            return self.render_template('claude.md.j2', context)
        except Exception:
            # Fallback to structured generation
            return self._generate_default_instructions(context)

    def _generate_default_instructions(self, context: Dict) -> str:
        """Generate default CLAUDE.md content (fallback)."""
        project = context.get('project', {})
        tech_stack = context.get('tech_stack', {})
        framework = context.get('framework', {})
        agents = context.get('agents', [])
        workflows = context.get('workflows', [])

        content = f"""# {project.get('name', 'Project')} - Claude Code Instructions

**Project Type:** {project.get('type', 'unknown')}
**Version:** {project.get('version', '1.0.0')}

{project.get('description', 'No description provided.')}

---

## Tech Stack

"""

        # Languages
        languages = tech_stack.get('languages', [])
        if languages:
            content += f"**Languages:** {', '.join(languages)}\n"

        # Frameworks
        frameworks = tech_stack.get('frameworks', [])
        if frameworks:
            content += f"**Frameworks:** {', '.join(frameworks)}\n"

        # Databases
        databases = tech_stack.get('databases', [])
        if databases:
            content += f"**Databases:** {', '.join(databases)}\n"

        content += "\n---\n\n"

        # Agents
        if agents:
            content += "## Available Agents\n\n"
            content += "This project uses the Vibey Agent Framework with the following specialized agents:\n\n"
            for agent in agents:
                agent_data = agent.get('agent', {})
                agent_id = agent_data.get('id', 'unknown')
                agent_name = agent_data.get('name', 'Unknown Agent')
                agent_desc = agent_data.get('description', 'No description')
                content += f"- **{agent_name}** (`{agent_id}`) - {agent_desc}\n"
            content += "\n"

        # Workflows
        if workflows:
            content += "## Available Workflows\n\n"
            for workflow in workflows:
                workflow_data = workflow.get('workflow', {})
                workflow_id = workflow_data.get('id', 'unknown')
                workflow_name = workflow_data.get('name', 'Unknown Workflow')
                workflow_desc = workflow_data.get('description', 'No description')
                content += f"- **{workflow_name}** (`{workflow_id}`) - {workflow_desc}\n"
            content += "\n"

        # Orchestration mode
        orchestration = framework.get('orchestration', {})
        if orchestration:
            mode = orchestration.get('mode', 'balanced')
            content += f"---\n\n## Orchestration Mode\n\n**Current Mode:** {mode}\n\n"

        content += "---\n\n"
        content += "<!-- VIBEY_FRAMEWORK_MANAGED -->\n"
        content += f"*Generated by Vibey Agent Framework for Claude Code*\n"

        return content

    def generate_agent_file(self, agent_config: Dict) -> str:
        """
        Generate agent file content for Claude Code.

        Uses agent.md.j2 template if available.
        """
        agent_data = agent_config.get('agent', {})

        # Prepare context
        context = {
            'agent': agent_data,
            'platform': 'claude-code'
        }

        # Try to render template
        try:
            return self.render_template('agent.md.j2', context)
        except Exception:
            # Fallback to structured generation
            return self._generate_default_agent(agent_data)

    def _generate_default_agent(self, agent_data: Dict) -> str:
        """Generate default agent content (fallback)."""
        agent_id = agent_data.get('id', 'unknown')
        agent_name = agent_data.get('name', 'Unknown Agent')
        description = agent_data.get('description', 'No description provided.')

        content = f"""# {agent_name}

**Agent ID:** {agent_id}

{description}

---

## Role and Purpose

{agent_data.get('role', 'No role defined.')}

---

## Trigger Patterns

"""

        triggers = agent_data.get('triggers', {})
        keywords = triggers.get('keywords', [])
        patterns = triggers.get('patterns', [])

        if keywords:
            content += "**Keywords:**\n"
            for keyword in keywords:
                content += f"- {keyword}\n"
            content += "\n"

        if patterns:
            content += "**Patterns:**\n"
            for pattern in patterns:
                content += f"- {pattern}\n"
            content += "\n"

        # Capabilities
        capabilities = agent_data.get('capabilities', [])
        if capabilities:
            content += "---\n\n## Capabilities\n\n"
            for capability in capabilities:
                content += f"- {capability}\n"
            content += "\n"

        # Quality criteria
        quality = agent_data.get('quality_criteria', [])
        if quality:
            content += "---\n\n## Quality Criteria\n\n"
            for criterion in quality:
                content += f"- {criterion}\n"
            content += "\n"

        content += "---\n\n"
        content += f"*Generated by Vibey Agent Framework*\n"

        return content

    def generate_workflow_file(self, workflow_config: Dict) -> str:
        """
        Generate workflow file content for Claude Code.

        Uses workflow.md.j2 template if available.
        """
        workflow_data = workflow_config.get('workflow', {})

        # Prepare context
        context = {
            'workflow': workflow_data,
            'platform': 'claude-code'
        }

        # Try to render template
        try:
            return self.render_template('workflow.md.j2', context)
        except Exception:
            # Fallback to structured generation
            return self._generate_default_workflow(workflow_data)

    def _generate_default_workflow(self, workflow_data: Dict) -> str:
        """Generate default workflow content (fallback)."""
        workflow_id = workflow_data.get('id', 'unknown')
        workflow_name = workflow_data.get('name', 'Unknown Workflow')
        description = workflow_data.get('description', 'No description provided.')

        content = f"""# {workflow_name}

**Workflow ID:** {workflow_id}

{description}

---

## Overview

**Duration:** {workflow_data.get('estimated_duration', 'Unknown')}
**Complexity:** {workflow_data.get('complexity', 'Medium')}

---

## Steps

"""

        steps = workflow_data.get('steps', [])
        for i, step in enumerate(steps, 1):
            step_name = step.get('name', f'Step {i}')
            step_desc = step.get('description', '')
            content += f"### {i}. {step_name}\n\n"
            if step_desc:
                content += f"{step_desc}\n\n"

            # Recommended agent
            agent = step.get('agent')
            if agent:
                content += f"**Recommended Agent:** {agent}\n\n"

            # Deliverables
            deliverables = step.get('deliverables', [])
            if deliverables:
                content += "**Deliverables:**\n"
                for deliverable in deliverables:
                    content += f"- {deliverable}\n"
                content += "\n"

        content += "---\n\n"
        content += f"*Generated by Vibey Agent Framework*\n"

        return content


def main():
    """Demo the Claude adapter."""
    print("🎯 Claude Code Platform Adapter\n")

    try:
        adapter = ClaudeAdapter()

        print(f"Platform: {adapter.get_platform_name()}")
        print(f"Deployment Directory: {adapter.get_deployment_dir()}")
        print(f"Instructions File: {adapter.get_instructions_filename()}\n")

        # Validate config
        print("Validating configuration...")
        if adapter.validate_config():
            print("✅ Configuration valid\n")

            # Generate deployment
            print("Generating deployment...\n")
            adapter.deploy(clean=False, validate=True, backup=True)
        else:
            print("❌ Configuration invalid\n")

    except FileNotFoundError as e:
        print(f"❌ {e}")
    except Exception as e:
        print(f"❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
